name: Build and Publish Update

on:
  push:
    branches: ['main']

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production

  publish_update:
    name: Publish Update
    type: update
    params:
      channel: production
      message: ${{ github.commit_message || 'Update' }}